package com.velo.app.engine

import java.io.File

/**
 * Transforms raw Android CookieManager strings into legacy Netscape HTTP Cookie File format
 * universally mandated by the yt-dlp python daemon for backend authentication.
 */
object CookieTranspiler {

    /**
     * Converts a raw semicolon-separated cookie string from Android's WebView into Netscape format
     * and saves it physically to the specified output file array.
     */
    fun saveToNetscapeFormat(
        rawCookies: String?,
        domain: String,
        outputFile: File
    ) {
        if (rawCookies.isNullOrBlank()) return

        val builder = java.lang.StringBuilder()
        builder.append("# Netscape HTTP Cookie File\n")
        builder.append("# This file was generated by Velo locally\n\n")

        val pairs = rawCookies.split(";").map { it.trim() }.filter { it.isNotEmpty() }
        
        for (pair in pairs) {
            val parts = pair.split("=", limit = 2)
            if (parts.size == 2) {
                val name = parts[0]
                val value = parts[1]
                
                // Format: domain \t include_subdomains \t path \t secure \t expiry \t name \t value
                val rootDomain = if (domain.startsWith(".")) domain else ".$domain"
                
                builder.append(rootDomain).append("\t")
                builder.append("TRUE").append("\t")
                builder.append("/").append("\t")
                builder.append("TRUE").append("\t")
                builder.append("2147483647").append("\t") // Expire in 2038
                builder.append(name).append("\t")
                builder.append(value).append("\n")
            }
        }

        outputFile.writeText(builder.toString())
    }
}
